repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=102400"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '^courses/ME-4710_Foundations_of_ML_for_Engineers/Homeworks/HW1/(Grains\.csv|co2py\.csv|iris_dataset\.csv|matweb-search-results\.html)$'
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: '^courses/ME-4710_Foundations_of_ML_for_Engineers/Homeworks/HW1/(Grains\.csv|co2py\.csv|iris_dataset\.csv|matweb-search-results\.html)$'
      - id: trailing-whitespace
        exclude: '(^courses/ME-4710_Foundations_of_ML_for_Engineers/Homeworks/HW1/(Grains\.csv|co2py\.csv|iris_dataset\.csv|matweb-search-results\.html)$|\.(patch|diff)$)'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-makefile
        name: check Makefile syntax
        entry: make --dry-run --silent
        language: system
        files: '(^|/)Makefile$'
        pass_filenames: false
